export const INIT_FIRESTORE = 'INIT_FIRESTORE';

// get posts
export const GET_POSTS_FROM_FIRESTORE_STARTED = 'GET_POSTS_FROM_FIRESTORE_STARTED';
export const SET_POSTS_FROM_FIRESTORE = 'SET_POSTS_FROM_FIRESTORE';
export const GET_POSTS_FROM_FIRESTORE_FAILURE = 'GET_POSTS_FROM_FIRESTORE_FAILURE';

// get users
export const GET_USERS_FROM_FIRESTORE_STARTED = 'GET_USERS_FROM_FIRESTORE_STARTED';
export const SET_USERS_FROM_FIRESTORE = 'SET_USERS_FROM_FIRESTORE';
export const GET_USERS_FROM_FIRESTORE_FAILURE = 'GET_USERS_FROM_FIRESTORE_FAILURE';

export const SIGN_IN = 'SIGN_IN';
export const GET_USERS_STARTED = 'GET_USERS_STARTED';
export const SET_USERS = 'SET_USERS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const CHECK_AMOUNT_OF_CHECKED_ELEMENT = 'CHECK_AMOUNT_OF_CHECKED_ELEMENT';

export const ADD_POST = 'ADD_POST';