// get posts
export const GET_POSTS_FROM_FIRESTORE_STARTED = 'GET_POSTS_FROM_FIRESTORE_STARTED';
export const SET_POSTS_FROM_FIRESTORE = 'SET_POSTS_FROM_FIRESTORE';
export const GET_POSTS_FROM_FIRESTORE_FAILURE = 'GET_POSTS_FROM_FIRESTORE_FAILURE';

// create new post
export const ON_CHANGE_POST = 'ON_CHANGE_POST';
export const GET_NEW_POST_STARTED = 'GET_NEW_POST_STARTED';
export const SET_NEW_POST = 'SET_NEW_POST';
export const GET_NEW_POST_FAILURE = 'GET_NEW_POST_FAILURE';

// delete post
export const DELETE_POST = 'DELETE_POST';

// delete friend
export const DELETE_FRIEND = 'DELETE_FRIEND';

// add friend
export const ADD_FRIEND = 'ADD_FRIEND';

// get users
export const GET_USERS_FROM_FIRESTORE_STARTED = 'GET_USERS_FROM_FIRESTORE_STARTED';
export const SET_USERS_FROM_FIRESTORE = 'SET_USERS_FROM_FIRESTORE';
export const GET_USERS_FROM_FIRESTORE_FAILURE = 'GET_USERS_FROM_FIRESTORE_FAILURE';

// auth
export const ON_CHANGE_EMAIL_SIGN_IN = 'ON_CHANGE_EMAIL_SIGN_IN';
export const ON_CHANGE_PASSWORD_SIGN_IN = 'ON_CHANGE_PASSWORD_SIGN_IN';
export const ON_CHANGE_EMAIL_SIGN_UP = 'ON_CHANGE_EMAIL_SIGN_UP';
export const ON_CHANGE_PASSWORD_SIGN_UP = 'ON_CHANGE_PASSWORD_SIGN_UP';

// sign up
export const SIGN_UP_STARTED = 'SIGN_UP_STARTED';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

// sign in
export const SIGN_IN_STARTED = 'SIGN_IN_STARTED';
export const SET_AUTHORIZED_USER = 'SET_AUTHORIZED_USER';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

// sign out
export const SIGN_OUT = 'SIGN_OUT';

// get authorized user's data
export const SET_AUTHORIZED_USER_DATA = 'SET_AUTHORIZED_USER_DATA';
export const GET_AUTHORIZED_USER_DATA_FAILURE = 'GET_AUTHORIZED_USER_DATA_FAILURE';

// get users (not firebase)
export const GET_USERS_STARTED = 'GET_USERS_STARTED';
export const SET_USERS = 'SET_USERS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

// edit profile
export const ON_CHANGE_FIRST_NAME = 'ON_CHANGE_FIRST_NAME';
export const ON_CHANGE_LAST_NAME = 'ON_CHANGE_LAST_NAME';
export const ON_CHANGE_HOME_TOWN = 'ON_CHANGE_HOME_TOWN';
export const ON_CHANGE_IMAGE = 'ON_CHANGE_IMAGE';

// set new fields in authorized user's data
export const SET_FIELDS_IN_AUTHORIZED_USER_DATA = 'SET_FIELDS_IN_AUTHORIZED_USER_DATA';